# Generated by Django 6.0.3 on 2026-03-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystock',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
