# Generated by Django 6.0.3 on 2026-03-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mystock_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mystock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mystock',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mystock',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
